version: "3.8"


services:
#  auth:
#    build:
#      dockerfile: auth.Dockerfile
#    container_name: auth
#    restart: always
#    hostname: auth
#    env_file:
#      - ./auth/.env
#    deploy:
#      resources:
#        limits:
#          cpus: '2'
#          memory: 250M
#    logging:
#      driver: "json-file"
#      options:
#        max-size: "50m"
#    healthcheck:
#      test: [ "CMD", "curl", "-f", "http://localhost:" ]
#      interval: 1m30s
#      timeout: 10s
#      retries: 3
#      start_period: 2m

  bookback:
    build:
      context: .
      dockerfile: bookback.Dockerfile
    container_name: bookback
    restart: always
    hostname: bookback
    env_file:
      - ./bookback/.env
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 250M
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
#    healthcheck:
#      test: [ "CMD", "curl", "-f", "http://localhost:" ]
#      interval: 3s
#      retries: 5
#      start_period: 30s

#  api_gateway:
#    build:
#      dockerfile: api_gateway.Dockerfile
#    container_name: api_gateway
#    restart: always
#    hostname: api_gateway
#    env_file:
#      - ./api_gateway/.env
#    deploy:
#      resources:
#        limits:
#          cpus: '2'
#          memory: 250M
#    logging:
#      driver: "json-file"
#      options:
#        max-size: "50m"
#    healthcheck:
#      test: [ "CMD", "curl", "-f", "http://localhost:" ]
#      interval: 3s
#      retries: 5
#      start_period: 30s

networks:
  backnet:
    driver: bridge