version: "3.8"


services:
  etcd0:
    image: bitnami/etcd:3.5.13
    container_name: etcd0
    restart: always
    env_file:
      - ./systems/etcd/.env
    ports:
      - "2379:2379"
      - "2380:2380"
    volumes:
      - ./systems/etcd/etcd_data/snapshots:/snapshots
      - ./systems/etcd/etcd_data/data:/bitnami/etcd/data
      - ./systems/etcd/conf.yaml:/opt/bitnami/Etcd/conf/etcd.conf.yml

  auth:
    build:
      context: .
      dockerfile: auth/Dockerfile
    container_name: auth
    restart: always
    hostname: auth
    ports:
      - "50051:50051"
    env_file:
      - ./auth/.env
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 250M
#    healthcheck:
#      test: [ "CMD", "curl", "-f", "http://localhost:" ]
#      interval: 1m30s
#      timeout: 10s
#      retries: 3
#      start_period: 2m

  bookback:
    build:
      context: .
      dockerfile: bookback/Dockerfile
    container_name: bookback
    restart: always
    hostname: bookback
    depends_on:
      - auth
    env_file:
      - ./bookback/.env
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 250M
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
#    healthcheck:
#      test: [ "CMD", "curl", "-f", "http://localhost:" ]
#      interval: 3s
#      retries: 5
#      start_period: 30s

  api_gateway:
    build:
      context: .
      dockerfile: api_gateway/Dockerfile
    container_name: api_gateway
    restart: always
    hostname: api_gateway
    ports:
      - "8930:8930"
    depends_on:
      - auth
      - bookback
    env_file:
      - ./api_gateway/.env
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 250M
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
#    healthcheck:
#      test: [ "CMD", "curl", "-f", "http://localhost:" ]
#      interval: 3s
#      retries: 5
#      start_period: 30s

networks:
  backnet:
    driver: bridge