package errors

const (
	ValidationFailed       = "Ошибка валидации полей ввода! Проверьте введенные данные и попробуйте снова."
	Unknown                = "Неизвестная ошибка"
	BookNotFound           = "Книга не найдена"
	BookNotCreated         = "Ошибка создания книги. Книга с такими параметрами уже существует."
	BookNotDeleted         = "Ошибка удаления книги"
	BookEventNotFound      = "Событие книги не найдено"
	BookEventNotCreated    = "Ошибка создания события книги. Событие с такими параметрами уже существует."
	BookEventNotDeleted    = "Ошибка удаления события книги"
	ChapterNotFound        = "Глава не найдена"
	ChapterNotCreated      = "Ошибка создания главы. Глава с такими параметрами уже существует."
	ChapterNotDeleted      = "Ошибка удаления главы"
	MapVariablesNotFound   = "Переменные карты не найдены"
	MapVariablesNotCreated = "Ошибка создания переменных карты. Переменные с такими параметрами уже существуют."
	MapVariablesNotDeleted = "Ошибка удаления переменных карты"
	PageNotFound           = "Страница не найдена"
	PageNotCreated         = "Ошибка создания страницы. Страница с такими параметрами уже существует."
	PageNotDeleted         = "Ошибка удаления страницы"
	ParagraphNotFound      = "Параграф не найден"
	ParagraphNotCreated    = "Ошибка создания параграфа. Параграф с такими параметрами уже существует."
	ParagraphNotDeleted    = "Ошибка удаления параграфа"
	MinioObjectNotCreated  = "Ошибка создания объекта Minio"
	MinioObjectNotFound    = "Объект Minio не найден"
)
