// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/SShlykov/zeitment/bookback/internal/domain/repository/pgrepo (interfaces: MapVariablesRepo)
//
// Generated by this command:
//
//	mockgen -destination=../../../../tests/mocks/domain/repository/pgrepo/map_variables_repo_mock.go -package=mocks github.com/SShlykov/zeitment/bookback/internal/domain/repository/pgrepo MapVariablesRepo
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	"github.com/SShlykov/zeitment/bookback/internal/infrastructure/repository/entity"
	"github.com/SShlykov/zeitment/postgres/dbutils"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockMapVariablesRepo is a mock of MapVariablesRepo interface.
type MockMapVariablesRepo struct {
	ctrl     *gomock.Controller
	recorder *MockMapVariablesRepoMockRecorder
}

// MockMapVariablesRepoMockRecorder is the mock recorder for MockMapVariablesRepo.
type MockMapVariablesRepoMockRecorder struct {
	mock *MockMapVariablesRepo
}

// NewMockMapVariablesRepo creates a new mock instance.
func NewMockMapVariablesRepo(ctrl *gomock.Controller) *MockMapVariablesRepo {
	mock := &MockMapVariablesRepo{ctrl: ctrl}
	mock.recorder = &MockMapVariablesRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMapVariablesRepo) EXPECT() *MockMapVariablesRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockMapVariablesRepo) Create(arg0 context.Context, arg1 *entity.MapVariable) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockMapVariablesRepoMockRecorder) Create(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockMapVariablesRepo)(nil).Create), arg0, arg1)
}

// FindByID mocks base method.
func (m *MockMapVariablesRepo) FindByID(arg0 context.Context, arg1 string) (*entity.MapVariable, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", arg0, arg1)
	ret0, _ := ret[0].(*entity.MapVariable)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockMapVariablesRepoMockRecorder) FindByID(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockMapVariablesRepo)(nil).FindByID), arg0, arg1)
}

// FindByKV mocks base method.
func (m *MockMapVariablesRepo) FindByKV(arg0 context.Context, arg1 dbutils.QueryOptions) ([]*entity.MapVariable, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByKV", arg0, arg1)
	ret0, _ := ret[0].([]*entity.MapVariable)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByKV indicates an expected call of FindByKV.
func (mr *MockMapVariablesRepoMockRecorder) FindByKV(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByKV", reflect.TypeOf((*MockMapVariablesRepo)(nil).FindByKV), arg0, arg1)
}

// HardDelete mocks base method.
func (m *MockMapVariablesRepo) HardDelete(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HardDelete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// HardDelete indicates an expected call of HardDelete.
func (mr *MockMapVariablesRepoMockRecorder) HardDelete(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HardDelete", reflect.TypeOf((*MockMapVariablesRepo)(nil).HardDelete), arg0, arg1)
}

// List mocks base method.
func (m *MockMapVariablesRepo) List(arg0 context.Context, arg1 dbutils.Pagination) ([]*entity.MapVariable, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1)
	ret0, _ := ret[0].([]*entity.MapVariable)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockMapVariablesRepoMockRecorder) List(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockMapVariablesRepo)(nil).List), arg0, arg1)
}

// Update mocks base method.
func (m *MockMapVariablesRepo) Update(arg0 context.Context, arg1 string, arg2 *entity.MapVariable) (*entity.MapVariable, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1, arg2)
	ret0, _ := ret[0].(*entity.MapVariable)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockMapVariablesRepoMockRecorder) Update(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockMapVariablesRepo)(nil).Update), arg0, arg1, arg2)
}
