// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/SShlykov/zeitment/bookback/internal/domain/repository/pgrepo (interfaces: PageRepo)
//
// Generated by this command:
//
//	mockgen -destination=../../../../tests/mocks/domain/repository/pgrepo/page_repo_mock.go -package=mocks github.com/SShlykov/zeitment/bookback/internal/domain/repository/pgrepo PageRepo
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	"github.com/SShlykov/zeitment/bookback/internal/infrastructure/repository/entity"
	"github.com/SShlykov/zeitment/postgres/dbutils"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPageRepo is a mock of PageRepo interface.
type MockPageRepo struct {
	ctrl     *gomock.Controller
	recorder *MockPageRepoMockRecorder
}

// MockPageRepoMockRecorder is the mock recorder for MockPageRepo.
type MockPageRepoMockRecorder struct {
	mock *MockPageRepo
}

// NewMockPageRepo creates a new mock instance.
func NewMockPageRepo(ctrl *gomock.Controller) *MockPageRepo {
	mock := &MockPageRepo{ctrl: ctrl}
	mock.recorder = &MockPageRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPageRepo) EXPECT() *MockPageRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPageRepo) Create(arg0 context.Context, arg1 *entity.Page) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockPageRepoMockRecorder) Create(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPageRepo)(nil).Create), arg0, arg1)
}

// FindByID mocks base method.
func (m *MockPageRepo) FindByID(arg0 context.Context, arg1 string) (*entity.Page, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", arg0, arg1)
	ret0, _ := ret[0].(*entity.Page)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockPageRepoMockRecorder) FindByID(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockPageRepo)(nil).FindByID), arg0, arg1)
}

// FindByKV mocks base method.
func (m *MockPageRepo) FindByKV(arg0 context.Context, arg1 dbutils.QueryOptions) ([]*entity.Page, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByKV", arg0, arg1)
	ret0, _ := ret[0].([]*entity.Page)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByKV indicates an expected call of FindByKV.
func (mr *MockPageRepoMockRecorder) FindByKV(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByKV", reflect.TypeOf((*MockPageRepo)(nil).FindByKV), arg0, arg1)
}

// HardDelete mocks base method.
func (m *MockPageRepo) HardDelete(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HardDelete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// HardDelete indicates an expected call of HardDelete.
func (mr *MockPageRepoMockRecorder) HardDelete(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HardDelete", reflect.TypeOf((*MockPageRepo)(nil).HardDelete), arg0, arg1)
}

// List mocks base method.
func (m *MockPageRepo) List(arg0 context.Context, arg1 dbutils.Pagination) ([]*entity.Page, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1)
	ret0, _ := ret[0].([]*entity.Page)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockPageRepoMockRecorder) List(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockPageRepo)(nil).List), arg0, arg1)
}

// Update mocks base method.
func (m *MockPageRepo) Update(arg0 context.Context, arg1 string, arg2 *entity.Page) (*entity.Page, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1, arg2)
	ret0, _ := ret[0].(*entity.Page)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockPageRepoMockRecorder) Update(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockPageRepo)(nil).Update), arg0, arg1, arg2)
}
