name: vue

on:
  push:
    branches:
      - main
      - books-ui
  pull_request:
    branches:
      - main
      - books-ui


jobs:
  lint-books-ui:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1


