name: vue

on:
  push:
    branches:
      - main
      - books-ui
  pull_request:
    branches:
      - main
      - books-ui


jobs:
  lint-books-ui:
    runs-on: ubuntu-latest
    steps:
      - name: log
        run: echo github.ref

      - name: Extract branch name
        run: echo "BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v4.1.1

